services:
  api-utilisateur:
    build:
      context: ./Back/microService-utilisateur
    container_name: api-utilisateur
    ports:
      - "8083:8081"
    networks:
      - medilabo-net
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api-patient:
    build:
      context: ./Back/microService-patient
    container_name: api-patient
    ports:
      - "8081:8081"
    networks:
      - medilabo-net
    environment:
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  gateway:
    build:
      context: ./gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      api-patient:
        condition: service_healthy
      api-utilisateur:
        condition: service_healthy
    networks:
      - medilabo-net
    environment:
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    build:
      context: ./Front/medilabo
    container_name: medilabo-frontend
    ports:
      - "3000:80"
    networks:
      - medilabo-net
    depends_on:
      gateway:
        condition: service_started
        
networks:
  medilabo-net:
    driver: bridge

