name: CI - Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & Run avec Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d
        sleep 15 # attendre un peu que les services soient prêts
        docker ps

    - name: Vérifier que les services tournent
      run: docker-compose ps

    - name: Arrêt des conteneurs
      run: docker-compose down
