name: CI - Docker Compose et Tests d'Intégration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 0
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SPRING_DATA_MONGODB_URI: ${{ secrets.SPRING_DATA_MONGODB_URI }}
	  SPRING_DATA_POSTGRE_URI: ${{secrets.SPRING_DATA_POSTGRE_URI}}

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Setup Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Build des microservices (sans les tests)
      run: |
        echo "Build du microservice utilisateur..."
        cd Back/microService-utilisateur && ./mvnw package -DskipTests && cd -
        echo "Build du microservice patient..."
        cd Back/microService-patient && ./mvnw package -DskipTests && cd -
        echo "Build du microservice gateway..."
        cd gateway && ./mvnw package -DskipTests && cd -

    - name: Lancer les tests unitaires des microservices
      run: |
        echo "Exécution des tests unitaires du microservice utilisateur..."
        cd Back/microService-utilisateur && ./mvnw test && cd -
        echo "Exécution des tests unitaires du microservice patient..."
        cd Back/microService-patient && ./mvnw test && cd -
        echo "Exécution des tests unitaires de la gateway..."
        cd gateway && ./mvnw test && cd -

    - name: Build & Run des conteneurs avec Docker Compose
      run: |
        echo "Démarrage des conteneurs Docker..."
        docker compose -f docker-compose.yml up --build -d
        echo "Conteneurs démarrés, attente pour la disponibilité des services..."
    
    - name: Vérifier l'état des conteneurs Docker
      run: docker compose ps

    - name: Lancer les tests d'intégration des microservices
      run: |
        echo "Exécution des tests d'intégration du microservice utilisateur..."
        cd Back/microService-utilisateur && ./mvnw verify && cd -

        echo "Exécution des tests d'intégration du microservice patient..."
        cd Back/microService-patient && ./mvnw verify && cd -

        echo "Exécution des tests d'intégration de la gateway..."
        cd gateway && ./mvnw verify && cd -

    - name: Arrêt des conteneurs Docker
      if: always()
      run: |
        echo "Arrêt des conteneurs Docker..."
        docker compose down
