name: CI - Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 0

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Setup Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build du microservice utilisateur
      run: |
        cd Back/microService-utilisateur && ./mvnw package -DskipTests

    - name: Build du microservice patient
      run: |
        cd Back/microService-patient && ./mvnw package -DskipTests

    - name: Build du microservice transmission
      run: |
        cd Back/microService-transmission && ./mvnw package -DskipTests

    - name: Build du microservice anticipation
      run: |
        cd Back/microService-anticipation && ./mvnw package -DskipTests

    - name: Vérifier le contenu du dossier utilisateur
      run: |
        echo "Contenu de Back/microService-utilisateur/target :"
        ls -l Back/microService-utilisateur/target

    - name: Vérifier le contenu du dossier patient
      run: |
        echo "Contenu de Back/microService-patient/target :"
        ls -l Back/microService-patient/target

    - name: Vérifier le contenu du dossier transmission
      run: |
        echo "Contenu de Back/microService-transmission/target :"
        ls -l Back/microService-transmission/target

    - name: Vérifier le contenu du dossier anticipation
      run: |
        echo "Contenu de Back/microService-anticipation/target :"
        ls -l Back/microService-anticipation/target

    - name: Build & Run avec Docker Compose
      run: |
        docker compose -f docker-compose.yml up --build -d
        sleep 15
        docker compose ps

    - name: Arrêt des conteneurs
      run: docker compose down
