name: CI - Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 0

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Vérifier les dossiers Back et leur contenu
      run: |
        echo "Contenu de Back/microService-utilisateur :"
        ls -l Back/microService-utilisateur

        echo "Contenu de Back/microService-patient :"
        ls -l Back/microService-patient

        echo "Contenu de Back/microService-transmission :"
        ls -l Back/microService-transmission

        echo "Contenu de Back/microService-anticipation :"
        ls -l Back/microService-anticipation

    - name: Build & Run avec Docker Compose
      run: |
        docker compose -f docker-compose.yml up --build -d
        sleep 15
        docker compose ps

    - name: Arrêt des conteneurs
      run: docker compose down
