name: CI - Docker Compose et Tests d'Intégration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 0

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Setup Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Build des microservices (sans les tests)
      run: |
        echo "Build du microservice utilisateur..."
        cd Back/microService-utilisateur && ./mvnw package -DskipTests && cd -
        echo "Build du microservice patient..."
        cd Back/microService-patient && ./mvnw package -DskipTests && cd -
        echo "Build du microservice gateway..."
        cd gateway && ./mvnw package -DskipTests && cd -

    - name: Lancer les tests unitaires des microservices
      run: |
        echo "Exécution des tests unitaires du microservice utilisateur..."
        cd Back/microService-utilisateur && ./mvnw test && cd -
        echo "Exécution des tests unitaires du microservice patient..."
        cd Back/microService-patient && ./mvnw test && cd -
        echo "Exécution des tests unitaires de la gateway..."
        cd gateway && ./mvnw test && cd -

    - name: Build & Run des conteneurs avec Docker Compose
      run: |
        echo "Démarrage des conteneurs Docker..."
        docker compose -f docker-compose.yml up --build -d
        echo "Conteneurs démarrés, attente pour la disponibilité des services..."
    
    # --- DÉBUT DES MODIFICATIONS ---
    - name: Attendre que les services soient prêts (Health Checks)
      run: |
        echo "Vérification de la disponibilité des services..."

        # 1. Attente pour la gateway elle-même
        # C'est la première étape, car c'est le point d'entrée
        until curl --fail http://localhost:8080/actuator/health; do
          echo 'Attente de la disponibilité de la gateway...'
          sleep 5
        done
        echo 'Gateway est disponible.'
        
        # 2. Attente pour api-patient (via la Gateway)
        # La Gateway est maintenant prête à router
        until curl --fail http://localhost:8080/patient/actuator/health; do
          echo 'Attente de la disponibilité de api-patient via la Gateway...'
          sleep 5
        done
        echo 'api-patient est disponible.'
        
        # 3. Attente pour api-utilisateur (via la Gateway)
        # La Gateway est prête à router
        until curl --fail http://localhost:8080/utilisateur/actuator/health; do
          echo 'Attente de la disponibilité de api-utilisateur via la Gateway...'
          sleep 5
        done
        echo 'api-utilisateur est disponible.'

        echo "Tous les services nécessaires sont démarrés et prêts."
    # --- FIN DES MODIFICATIONS ---

    - name: Vérifier l'état des conteneurs Docker
      run: docker compose ps

    - name: Lancer les tests d'intégration des microservices
      run: |
        echo "Exécution des tests d'intégration du microservice utilisateur..."
        cd Back/microService-utilisateur && ./mvnw verify && cd -

        echo "Exécution des tests d'intégration du microservice patient..."
        cd Back/microService-patient && ./mvnw verify && cd -

        echo "Exécution des tests d'intégration de la gateway..."
        cd gateway && ./mvnw verify && cd -

    - name: Arrêt des conteneurs Docker
      if: always()
      run: |
        echo "Arrêt des conteneurs Docker..."
        docker compose down
